const express = require('express');
const auth = require('../middleware/auth');
const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle, convertInchesToTwip } = require('docx');
const PDFDocument = require('pdfkit');

const router = express.Router();

// ─── Helper: parse Markdown-like content into structured blocks ───────────
const parseContent = (text) => {
  const blocks = [];
  const lines = text.split('\n');

  lines.forEach(line => {
    const trimmed = line.trim();
    if (!trimmed) return;

    if (/^# /.test(trimmed)) {
      blocks.push({ type: 'h1', text: trimmed.replace(/^# /, '') });
    } else if (/^## /.test(trimmed)) {
      blocks.push({ type: 'h2', text: trimmed.replace(/^## /, '') });
    } else if (/^### /.test(trimmed)) {
      blocks.push({ type: 'h3', text: trimmed.replace(/^### /, '') });
    } else if (/^[-•*] /.test(trimmed)) {
      blocks.push({ type: 'bullet', text: trimmed.replace(/^[-•*] /, '') });
    } else if (/^\d+\. /.test(trimmed)) {
      blocks.push({ type: 'numbered', text: trimmed.replace(/^\d+\. /, '') });
    } else {
      blocks.push({ type: 'paragraph', text: trimmed });
    }
  });

  return blocks;
};

// ─── Strip inline markdown (*bold*, _italic_, etc.) ───────────────────────
const stripMarkdown = (text) =>
  text
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/`(.+?)`/g, '$1')
    .replace(/_(.+?)_/g, '$1');

// ─── POST /api/export/docx ────────────────────────────────────────────────
router.post('/docx', auth, async (req, res) => {
  try {
    const { content, title = 'Document', topic = '', formatting = {} } = req.body;

    const font = formatting.font || 'Calibri';
    const bodySize = (formatting.fontSize || 12) * 2;
    const headingColor = (formatting.headingColor || '#1e1b4b').replace('#', '');
    const bodyColor = (formatting.bodyColor || '#374151').replace('#', '');
    const align = formatting.alignment === 'center' ? AlignmentType.CENTER
      : formatting.alignment === 'right' ? AlignmentType.RIGHT
      : formatting.alignment === 'justify' ? AlignmentType.JUSTIFIED
      : AlignmentType.LEFT;

    const blocks = parseContent(content);
    const docChildren = [];

    // Title
    docChildren.push(new Paragraph({
      children: [new TextRun({ text: title, bold: true, size: 56, font, color: headingColor })],
      heading: HeadingLevel.TITLE,
      spacing: { after: 200 },
    }));

    if (topic) {
      docChildren.push(new Paragraph({
        children: [new TextRun({ text: `Topic: ${topic}`, size: 24, font, color: '6366f1', italics: true })],
        spacing: { after: 400 },
      }));
    }

    blocks.forEach(block => {
      if (block.type === 'h1') {
        docChildren.push(new Paragraph({
          children: [new TextRun({ text: stripMarkdown(block.text), bold: true, size: 40, font, color: headingColor })],
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 160 },
        }));
      } else if (block.type === 'h2') {
        docChildren.push(new Paragraph({
          children: [new TextRun({ text: stripMarkdown(block.text), bold: true, size: 32, font, color: headingColor })],
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 300, after: 120 },
        }));
      } else if (block.type === 'h3') {
        docChildren.push(new Paragraph({
          children: [new TextRun({ text: stripMarkdown(block.text), bold: true, size: 26, font, color: headingColor })],
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 200, after: 80 },
        }));
      } else if (block.type === 'bullet') {
        docChildren.push(new Paragraph({
          children: [new TextRun({ text: '• ' + stripMarkdown(block.text), size: bodySize, font, color: bodyColor })],
          indent: { left: convertInchesToTwip(0.3) },
          spacing: { before: 40, after: 40 },
          alignment: align,
        }));
      } else if (block.type === 'numbered') {
        docChildren.push(new Paragraph({
          children: [new TextRun({ text: stripMarkdown(block.text), size: bodySize, font, color: bodyColor })],
          numbering: { reference: 'numbering', level: 0 },
          spacing: { before: 40, after: 40 },
          alignment: align,
        }));
      } else {
        docChildren.push(new Paragraph({
          children: block.text.split(/\*\*(.+?)\*\*/).map((part, i) =>
            i % 2 === 1
              ? new TextRun({ text: part, bold: true, size: bodySize, font, color: bodyColor })
              : new TextRun({ text: part, size: bodySize, font, color: bodyColor })
          ),
          spacing: { before: 80, after: 80 },
          alignment: align,
        }));
      }
    });

    // Footer
    docChildren.push(new Paragraph({
      children: [new TextRun({ text: `Generated by DocCraft AI — ${new Date().toLocaleDateString()}`, size: 18, font, color: '94a3b8', italics: true })],
      spacing: { before: 600 },
      alignment: AlignmentType.CENTER,
    }));

    const doc = new Document({
      sections: [{
        properties: {
          page: {
            margin: {
              top: formatting.margins?.top || 1080,
              bottom: formatting.margins?.bottom || 1080,
              left: formatting.margins?.left || 1440,
              right: formatting.margins?.right || 1440,
            },
          },
        },
        children: docChildren,
      }],
    });

    const buffer = await Packer.toBuffer(doc);
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    res.setHeader('Content-Disposition', `attachment; filename="${title.replace(/[^a-z0-9]/gi, '_')}.docx"`);
    res.send(buffer);
  } catch (err) {
    console.error('DOCX export error:', err);
    res.status(500).json({ success: false, message: 'DOCX export failed', error: err.message });
  }
});

// ─── POST /api/export/pdf ─────────────────────────────────────────────────
router.post('/pdf', auth, async (req, res) => {
  try {
    const { content, title = 'Document', topic = '', formatting = {} } = req.body;

    const font = 'Helvetica'; // PDFKit built-in
    const bodyFontSize = formatting.fontSize || 12;
    const blocks = parseContent(content);

    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 72, bottom: 72, left: 80, right: 80 },
      info: { Title: title, Author: 'DocCraft AI', Subject: topic },
    });

    const buffers = [];
    doc.on('data', chunk => buffers.push(chunk));
    doc.on('end', () => {
      const pdfBuffer = Buffer.concat(buffers);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="${title.replace(/[^a-z0-9]/gi, '_')}.pdf"`);
      res.send(pdfBuffer);
    });

    // Title
    doc.fontSize(28).font('Helvetica-Bold').fillColor('#1e1b4b').text(title, { align: 'left' });
    if (topic) {
      doc.fontSize(13).font('Helvetica-Oblique').fillColor('#6366f1').text(`Topic: ${topic}`, { align: 'left' });
    }
    doc.moveDown(0.5);
    doc.strokeColor('#6366f1').lineWidth(1).moveTo(80, doc.y).lineTo(515, doc.y).stroke();
    doc.moveDown(1);

    const align = formatting.alignment || 'left';

    blocks.forEach(block => {
      const text = stripMarkdown(block.text);
      if (block.type === 'h1') {
        doc.moveDown(0.6);
        doc.fontSize(20).font('Helvetica-Bold').fillColor('#1e1b4b').text(text, { align });
        doc.moveDown(0.3);
        doc.strokeColor('#a5b4fc').lineWidth(0.5).moveTo(80, doc.y).lineTo(515, doc.y).stroke();
        doc.moveDown(0.4);
      } else if (block.type === 'h2') {
        doc.moveDown(0.5);
        doc.fontSize(16).font('Helvetica-Bold').fillColor('#312e81').text(text, { align });
        doc.moveDown(0.3);
      } else if (block.type === 'h3') {
        doc.moveDown(0.4);
        doc.fontSize(13).font('Helvetica-Bold').fillColor('#4338ca').text(text, { align });
        doc.moveDown(0.2);
      } else if (block.type === 'bullet') {
        doc.fontSize(bodyFontSize).font('Helvetica').fillColor('#374151')
          .text('• ' + text, { align: 'left', indent: 15, lineGap: 2 });
        doc.moveDown(0.1);
      } else if (block.type === 'numbered') {
        doc.fontSize(bodyFontSize).font('Helvetica').fillColor('#374151')
          .text(text, { align, indent: 15, lineGap: 2 });
        doc.moveDown(0.1);
      } else {
        doc.fontSize(bodyFontSize).font('Helvetica').fillColor('#374151')
          .text(text, { align, lineGap: 3 });
        doc.moveDown(0.4);
      }
    });

    // Footer
    doc.moveDown(2);
    const pageCount = doc.bufferedPageRange().count;
    doc.fontSize(9).font('Helvetica-Oblique').fillColor('#94a3b8')
      .text(`Generated by DocCraft AI — ${new Date().toLocaleDateString()}`, { align: 'center' });

    doc.end();
  } catch (err) {
    console.error('PDF export error:', err);
    res.status(500).json({ success: false, message: 'PDF export failed', error: err.message });
  }
});

module.exports = router;
